spring:
  application:
    name: weather-service-api
    description: API for weather service
    version: 1.0.0

info:
  application:
    name: weather-service-api
    description: API for weather service
    version: 1.0.0

server:
  port: 8081

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#ANDUVO CON ESTO!!!
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info